[package]
name = "educe"
version = "0.0.3"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2018"
repository = "https://github.com/magiclen/educe"
homepage = "https://magiclen.org/educe"
keywords = ["derive", "macro", "trait", "debug", "procedural"]
categories = ["no-std", "rust-patterns"]
description= "This crate provides procedural macros to help you implement Rust-build-in traits quickly."
readme = "README.md"
license = "MIT"

[badges]
travis-ci = { repository = "magiclen/educe", branch = "master" }
appveyor = { repository = "magiclen/educe", branch = "master", service = "github" }

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
syn = {version = "0.15", features = ["full"]}
quote = "0.6"
