[package]
name = "educe"
version = "0.2.0"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2018"
repository = "https://github.com/magiclen/educe"
homepage = "https://magiclen.org/educe"
keywords = ["derive", "macro", "trait", "field", "procedural"]
categories = ["no-std", "rust-patterns"]
description= "This crate provides procedural macros to help you implement Rust-built-in traits quickly."
readme = "README.md"
license = "MIT"

[badges.travis-ci]
repository = "magiclen/educe"
branch = "master"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
syn = { version = "0.15", features = ["full"] }
quote = "0.6"
